-- MySQL Script generated by MySQL Workbench
-- Wed Oct 16 08:06:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdihelp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bdihelp` ;

-- -----------------------------------------------------
-- Schema bdihelp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdihelp` DEFAULT CHARACTER SET utf8 ;
USE `bdihelp` ;

-- -----------------------------------------------------
-- Table `bdihelp`.`Colaboradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdihelp`.`Colaboradores` ;

CREATE TABLE IF NOT EXISTS `bdihelp`.`Colaboradores` (
  `codColaborador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `datadeNascimento` VARCHAR(45) NULL,
  `curso` VARCHAR(100) NULL,
  `instituicao` VARCHAR(100) NULL,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL DEFAULT 'pass',
  `email` VARCHAR(100) NOT NULL DEFAULT '@',
  `apelido` VARCHAR(45) NOT NULL DEFAULT 'nick',
  `sexo` VARCHAR(50) NULL,
  `niveldeEscolaridade` VARCHAR(100) NULL,
  `cidade` VARCHAR(50) NULL,
  `estado` VARCHAR(50) NULL,
  `niveldoColaborador` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codColaborador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdihelp`.`Topicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdihelp`.`Topicos` ;

CREATE TABLE IF NOT EXISTS `bdihelp`.`Topicos` (
  `codTopico` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `dataCriacao` DATE NOT NULL,
  `horaCriacao` TIME NOT NULL,
  `fk_codColaborador` INT NOT NULL,
  PRIMARY KEY (`codTopico`),
  INDEX `fk_Topicos_Colaboradores1_idx` (`fk_codColaborador` ASC) VISIBLE,
  CONSTRAINT `fk_Topicos_Colaboradores1`
    FOREIGN KEY (`fk_codColaborador`)
    REFERENCES `bdihelp`.`Colaboradores` (`codColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdihelp`.`Subtopicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdihelp`.`Subtopicos` ;

CREATE TABLE IF NOT EXISTS `bdihelp`.`Subtopicos` (
  `codTopicos` INT NOT NULL AUTO_INCREMENT,
  `assunto` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(500) NULL,
  `datadeCriacao` DATE NOT NULL,
  `horadeCriacao` TIME NOT NULL,
  `fk_codTopico` INT NOT NULL,
  PRIMARY KEY (`codTopicos`),
  INDEX `fk_Subtopicos_Topicos_idx` (`fk_codTopico` ASC) VISIBLE,
  CONSTRAINT `fk_Subtopicos_Topicos`
    FOREIGN KEY (`fk_codTopico`)
    REFERENCES `bdihelp`.`Topicos` (`codTopico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdihelp`.`Perguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdihelp`.`Perguntas` ;

CREATE TABLE IF NOT EXISTS `bdihelp`.`Perguntas` (
  `codPergunta` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `niveldaPergunta` INT NOT NULL,
  `Pergunta` VARCHAR(500) NOT NULL,
  `fk_codTopicos` INT NOT NULL,
  `fk_codColaborador` INT NOT NULL,
  PRIMARY KEY (`codPergunta`),
  INDEX `fk_Perguntas_Subtopicos1_idx` (`fk_codTopicos` ASC) VISIBLE,
  INDEX `fk_Perguntas_Colaboradores1_idx` (`fk_codColaborador` ASC) VISIBLE,
  CONSTRAINT `fk_Perguntas_Subtopicos1`
    FOREIGN KEY (`fk_codTopicos`)
    REFERENCES `bdihelp`.`Subtopicos` (`codTopicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Perguntas_Colaboradores1`
    FOREIGN KEY (`fk_codColaborador`)
    REFERENCES `bdihelp`.`Colaboradores` (`codColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdihelp`.`Respostas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdihelp`.`Respostas` ;

CREATE TABLE IF NOT EXISTS `bdihelp`.`Respostas` (
  `codResposta` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `Resposta` VARCHAR(500) NOT NULL,
  `fk_codPergunta` INT NOT NULL,
  INDEX `fk_Respostas_Perguntas1_idx` (`fk_codPergunta` ASC) VISIBLE,
  PRIMARY KEY (`codResposta`),
  CONSTRAINT `fk_Respostas_Perguntas1`
    FOREIGN KEY (`fk_codPergunta`)
    REFERENCES `bdihelp`.`Perguntas` (`codPergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdihelp`.`AvaliacaodaPergunta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdihelp`.`AvaliacaodaPergunta` ;

CREATE TABLE IF NOT EXISTS `bdihelp`.`AvaliacaodaPergunta` (
  `fk_codPergunta` INT NOT NULL,
  `fk_codColaborador` INT NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `nota` INT NOT NULL,
  PRIMARY KEY (`fk_codPergunta`, `fk_codColaborador`),
  INDEX `fk_AvaliacaodaPergunta_Colaboradores1_idx` (`fk_codColaborador` ASC) VISIBLE,
  CONSTRAINT `fk_AvaliacaodaPergunta_Perguntas1`
    FOREIGN KEY (`fk_codPergunta`)
    REFERENCES `bdihelp`.`Perguntas` (`codPergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AvaliacaodaPergunta_Colaboradores1`
    FOREIGN KEY (`fk_codColaborador`)
    REFERENCES `bdihelp`.`Colaboradores` (`codColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdihelp`.`AvaliacaodaResposta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdihelp`.`AvaliacaodaResposta` ;

CREATE TABLE IF NOT EXISTS `bdihelp`.`AvaliacaodaResposta` (
  `fk_codColaborador` INT NOT NULL,
  `fk_codResposta` INT NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `nota` INT NOT NULL,
  PRIMARY KEY (`fk_codColaborador`, `fk_codResposta`),
  INDEX `fk_AvaliacaodaResposta_Respostas1_idx` (`fk_codResposta` ASC) VISIBLE,
  CONSTRAINT `fk_AvaliacaodaResposta_Colaboradores1`
    FOREIGN KEY (`fk_codColaborador`)
    REFERENCES `bdihelp`.`Colaboradores` (`codColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AvaliacaodaResposta_Respostas1`
    FOREIGN KEY (`fk_codResposta`)
    REFERENCES `bdihelp`.`Respostas` (`codResposta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
